### ISSUE TITLE
Release 12.5.12 breaks jenkins cookbook on chef-client 12.5.1 & 12.4.3

### ISSUE THREAD

**Issue by Sauraus** [chef-cookbooks/compat_resource#16]
Release 12.5.10 is good and runs with no issues.
```
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/jenkins/libraries/slave_windows.rb
================================================================================

NameError
---------
undefined method `log_deprecation' for class `Class'

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:6:in `method'
  /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:6:in `log_deprecation'
  /var/chef/cache/cookbooks/jenkins/libraries/slave_windows.rb:29:in `<class:JenkinsWindowsSlave>'
  /var/chef/cache/cookbooks/jenkins/libraries/slave_windows.rb:27:in `<class:Chef>'
  /var/chef/cache/cookbooks/jenkins/libraries/slave_windows.rb:26:in `<top (required)>'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:

  1:  class Chef
  2:    NOT_PASSED = Object.new if !defined?(NOT_PASSED)
  3:    # Earlier versions of Chef didn't have this message
  4:    module ChefCompatDeprecation
  5:      def log_deprecation(message, location=nil)
  6>>       if superclass.method(:log_deprecation).owner != ChefCompatDeprecation
  7:          if !location
  8:            # Pick the first caller that is *not* part of the Chef or ChefCompat gem,
  9:            # that's the thing the user wrote.
 10:            chef_compat_gem_path = File.expand_path("../../..", __FILE__)
 11:            chef_gem_path = File.expand_path("../..",::Chef::Resource.instance_method(:initialize).source_location[0])
 12:            caller(0..10).each do |c|
 13:              if !c.start_with?(chef_gem_path) && !c.start_with?(chef_compat_gem_path)
 14:                location = c
 15:                break
```

**Comment by scalp42** [comment]
@Sauraus your error is fixed in https://github.com/chef-cookbooks/compat_resource/pull/13 and you'll need 12.5.13 version.

But 12.5.13 introduces another issue, see https://github.com/chef-cookbooks/compat_resource/issues/15

**Comment by lamont-granquist** [comment]
fixed in 12.5.14

**Comment by Sauraus** [comment]
Giving it a spin now

**Comment by Sauraus** [comment]
Works like a charm
