### ISSUE TITLE
NoMethodError "super: no superclass method `log_deprecation' for ChefCompat::CopiedFromChef::Chef:Class"

### ISSUE THREAD

**Issue by jperville** [chef-cookbooks/compat_resource#3]
Hello there,

Got the following error when trying to use the chef-docker version 2.0 cookbook (which depends on this cookbook to ensure compatibility with older chef 12 versions).

I am using chef 12.4.3 (x64), running on Ubuntu 14.04 virtual machine in test kitchen.

```
         NoMethodError
         -------------
       super: no superclass method `log_deprecation' for ChefCompat::CopiedFromChef::Chef:Class
       
         Cookbook Trace:
         ---------------
           /tmp/vagrant-cache/chef/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:20:in `log_deprecation'
         /tmp/vagrant-cache/chef/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/property.rb:258:in `call'
           /tmp/vagrant-cache/chef/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/property.rb:455:in `username'
           /tmp/vagrant-cache/chef/cookbooks/pm_docker_test/recipes/default.rb:5:in `block in from_file'
           /tmp/vagrant-cache/chef/cookbooks/pm_docker_test/recipes/default.rb:4:in `from_file'
```

Thank you very much

**Comment by teknofire** [comment]
Running into this as well on vm with 12.3.0 on Ubuntu 14.04

**Comment by spion06** [comment]
hitting this as well... caused random build failures starting today.

**Comment by danielsand** [comment]
im joining into the line - only under test-kitchen.

```
I, [2015-10-29T15:24:43.426944 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404: NameError
I, [2015-10-29T15:24:43.427082 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404: ---------
I, [2015-10-29T15:24:43.427226 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404: undefined method `log_deprecation' for class `Class'
I, [2015-10-29T15:24:43.427364 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404:
I, [2015-10-29T15:24:43.427484 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404: Cookbook Trace:
I, [2015-10-29T15:24:43.427628 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404: ---------------
I, [2015-10-29T15:24:43.427769 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404:   /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:6:in `method'
I, [2015-10-29T15:24:43.427913 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404:   /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:6:in `log_deprecation'
I, [2015-10-29T15:24:43.427947 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404:   /tmp/kitchen/cache/cookbooks/yum/resources/globalconfig.rb:77:in `class_from_file'
I, [2015-10-29T15:24:43.428148 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404:   /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource/lwrp_base.rb:50:in `build_from_file'
I, [2015-10-29T15:24:43.428267 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404:
I, [2015-10-29T15:24:43.428437 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404: Relevant File Content:
I, [2015-10-29T15:24:43.428556 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404: ----------------------
I, [2015-10-29T15:24:43.428674 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404: /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:
I, [2015-10-29T15:24:43.428706 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404:
I, [2015-10-29T15:24:43.428825 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404:   1:  class Chef
I, [2015-10-29T15:24:43.428997 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404:   2:    NOT_PASSED = Object.new if !defined?(NOT_PASSED)
I, [2015-10-29T15:24:43.429115 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404:   3:    # Earlier versions of Chef didn't have this message
I, [2015-10-29T15:24:43.429297 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404:   4:    module ChefCompatDeprecation
I, [2015-10-29T15:24:43.429470 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404:   5:      def log_deprecation(message, location=nil)
I, [2015-10-29T15:24:43.429585 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404:
I, [2015-10-29T15:24:43.429752 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404:   7:          if !location
I, [2015-10-29T15:24:43.429872 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404:   8:            # Pick the first caller that is *not* part of the Chef or ChefCompat gem,
I, [2015-10-29T15:24:43.430045 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404:   9:            # that's the thing the user wrote.
I, [2015-10-29T15:24:43.430218 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404:  10:            chef_compat_gem_path = File.expand_path("../../..", __FILE__)
I, [2015-10-29T15:24:43.430396 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404:  11:            chef_gem_path = File.expand_path("../..",::Chef::Resource.instance_method(:initialize).source_location[0])
I, [2015-10-29T15:24:43.430568 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404:  12:            caller(0..10).each do |c|
I, [2015-10-29T15:24:43.430687 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404:  13:              if !c.start_with?(chef_gem_path) && !c.start_with?(chef_compat_gem_path)
I, [2015-10-29T15:24:43.430719 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404:  14:                location = c
I, [2015-10-29T15:24:43.430836 #23718]  INFO -- thumbnailapi-ec2-ubuntu-1404:  15:                break
```

**Comment by aaron-lane** [comment]
:+1:

**Comment by rgriffith** [comment]
Just ran into the exact same error @danielsand listed during a chef-client run on a CentOS 6.5 node, but was coming from `ark`. Oddly, I wasn't seeing this error about an hour ago.

**Comment by jkeiser** [comment]
Fixed by #13 (and released).

**Comment by jperville** [comment]
Thank you very much @jkeiser :)

**Comment by lamont-granquist** [comment]
closing this since we no longer have this bug but have #15 instead...
