### ISSUE TITLE
Missing method 'action' since latest release

### ISSUE THREAD

**Issue by ianbamforth** [chef-cookbooks/compat_resource#33]
NoMethodError:
       undefined method `action' for #<Class:0x0000000506b8c8> action provider

Only seems to have occurred in the last few hours - was definitely ok 12 hours ago.  May not be your fault!

**Comment by puckel** [comment]
Hi,

Same here with openssh cookbook who depends > iptables > compat_ressource

```
================================================================================
Recipe Compile Error in /tmp/d20151221-27456-1qm8rci/cookbooks/iptables/resources/rule.rb
================================================================================

NoMethodError
-------------
undefined method `action' for #<Class:0x0000000a113050> action provider

Cookbook Trace:
---------------
  /tmp/d20151221-27456-1qm8rci/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/resource.rb:151:in `action'
  /tmp/d20151221-27456-1qm8rci/cookbooks/iptables/resources/rule.rb:25:in `class_from_file'
  /tmp/d20151221-27456-1qm8rci/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource/lwrp_base.rb:41:in `build_from_file'

Relevant File Content:
----------------------
/tmp/d20151221-27456-1qm8rci/cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/resource.rb:

144:      end
145:      def self.default_action=(action_name)
146:        default_action action_name
147:      end
148:      def self.action(action, &recipe_block)
149:        action = action.to_sym
150:        declare_action_class
151>>       action_class.action(action, &recipe_block)
152:        self.allowed_actions += [ action ]
153:        default_action action if Array(default_action) == [:nothing]
154:      end
155:      def self.load_current_value(&load_block)
156:        define_method(:load_current_value!, &load_block)
157:      end
158:      def current_value_does_not_exist!
159:        raise Chef::Exceptions::CurrentValueDoesNotExist
160:      end
```

**Comment by aaron-lane** [comment]
:+1:

**Comment by puckel** [comment]
Hi,

Any news about this issue ?

Thanks

**Comment by puckel** [comment]
Hi,

This issue is fixed for me since the last release of openssh cookbook (v2.0.2)

Thanks

**Comment by bogdangi** [comment]
Hi,

I have this issue as well but with docker cookbook.

```trace
Failure/Error: end.converge(described_recipe)
NoMethodError:
 undefined method `action' for DockerCookbook::DockerContainer action provider:Class
# ./cookbooks/compat_resource/files/lib/chef_compat/copied_from_chef/chef/resource.rb:151:in `action'
# ./cookbooks/docker/libraries/docker_container.rb:222:in `<class:DockerContainer>'
# ./cookbooks/docker/libraries/docker_container.rb:2:in `<module:DockerCookbook>'
# ./cookbooks/docker/libraries/docker_container.rb:1:in `<top (required)>'
# /home/bogdan/.chefdk/gem/ruby/2.1.0/gems/chefspec-4.3.0/lib/chefspec/solo_runner.rb:115:in `converge'
# ./cookbooks/f2-elastalert/spec/recipes/default_spec.rb:29:in `block (2 levels) in <top (required)>'
# ./cookbooks/f2-elastalert/spec/recipes/default_spec.rb:52:in `block (2 levels) in <top (required)>'
```

But it fails for tests.

Thanks.

**Comment by bogdangi** [comment]
Here is additional info  https://github.com/chef-cookbooks/compat_resource/commit/f0665cec7f9cb1763dea0cc98cafd9586c2749f1#commitcomment-15064785
I am using version 12.5.24 :(

**Comment by lamont-granquist** [comment]
pretty certain this was fixed, open a new issue if it still persists.
