### ISSUE TITLE
Deprecated features used with Chef: 12.5.1

### ISSUE THREAD

**Issue by tiago-cruz-movile** [chef-cookbooks/compat_resource#34]
"name": "compat_resource",
  "version": "12.5.26",

```
Deprecated features used!
  Using an LWRP provider by its name (Ark) directly is no longer supported in Chef 12 and will be removed.  Use Chef::ProviderResolver.new(node, resource, action) instead. at 1 location:
    - /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:20:in `log_deprecation'
  checksum nil currently does not overwrite the value of checksum. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :checksum, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:20:in `log_deprecation'
  cloud_credentials_username nil currently does not overwrite the value of cloud_credentials_username. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :cloud_credentials_username, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:20:in `log_deprecation'
  cloud_credentials_api_key nil currently does not overwrite the value of cloud_credentials_api_key. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :cloud_credentials_api_key, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:20:in `log_deprecation'
  alarm_criteria nil currently does not overwrite the value of alarm_criteria. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :alarm_criteria, [MyType, nil]", or stop setting this value to nil. at 1 location:
    - /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:20:in `log_deprecation'
  chef_gem[htauth] chef_gem compile_time installation is deprecated at 1 location:
    - /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:20:in `log_deprecation'
  chef_gem[htauth] Please set `compile_time false` on the resource to use the new behavior. at 1 location:
    - /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:20:in `log_deprecation'
  chef_gem[htauth] or set `compile_time true` on the resource if compile_time behavior is required. at 1 location:
    - /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb:20:in `log_deprecation'
```

**Comment by yshh** [comment]
I have encounterd this issue on Chef client 12.5.1.
When compat_resource cookbook is loaded, all of reported locations become `/path/to/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef.rb`.
So it's hard to find where the deprecated features are used.

It does not occur when I run Chef client 12.5.1 without this cookbook.
