### ISSUE TITLE
Custom resources - undefined method `split' for nil:NilClass

### ISSUE THREAD

**Issue by arthurbarr** [chef-cookbooks/compat_resource#39]
I am using a custom resource in Chef V12.6, which seems to work fine.  My cookbook depends on "compat_resource", which I think should allow the same cookbook to run on Chef V12.0.  However, I get the following error:

```
============================================================================
       Recipe Compile Error in /tmp/kitchen/cache/cookbooks/blah/resources/installation.rb      
============================================================================

       NoMethodError
       -------------
       undefined method `split' for nil:NilClass

       Cookbook Trace:
       ---------------
         /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/resource.rb:42:in `resource_name'
         /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/resource.rb:52:in `resource_name='
         /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource/lwrp_base.rb:41:
in `build_from_file'

       Relevant File Content:
       ----------------------
       /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/resource.rb:

        35:            # Set the resource_name and call provides
        36:            if name
        37:              name = name.to_sym
        38:              # If our class is not already providing this name, provide it.
        39:              # Commented out: use of resource_name and provides will need to be
        40:              # mutually exclusive in this world, generally.
        41:              # if !Chef::ResourceResolver.includes_handler?(name, self)
        42>>               provides name#, canonical: true
        43:              # end
        44:              @resource_name = name
        45:            else
        46:              @resource_name = nil
        47:            end
        48:          end
        49:          @resource_name
        50:        end
        51:        def self.resource_name=(name)
```

**Comment by lamont-granquist** [comment]
would need a lot more information such as a repeatable example to be able to solve this.

chef 12.0.0 is definitely not supported by this cookbook, the minimal version we test against is 12.0.3 -- 12.0.0 through 12.0.2 is known to be broken and will not be fixed.
