### ISSUE TITLE
uninitialized constant Chef::VERSION in 12.9.1

### ISSUE THREAD

**Issue by poliva83** [chef-cookbooks/compat_resource#51]
I am getting issues with 12.9.1 gem that was just pushed out today that I didn't see in earlier version.

```
poliva@poliva-chef-provisioning-ws4 /s/m/p/chef-nexus> irb
irb(main):001:0> require 'chef/nexus'
NameError: uninitialized constant Chef::VERSION
        from /home/poliva/.chefdk/gem/ruby/2.1.0/gems/compat_resource-12.9.1/files/lib/chef_compat/monkeypatches/chef/mixin/params_validate.rb:1:in `<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/poliva/.chefdk/gem/ruby/2.1.0/gems/compat_resource-12.9.1/files/lib/chef_compat/monkeypatches.rb:3:in `<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/poliva/.chefdk/gem/ruby/2.1.0/gems/compat_resource-12.9.1/files/lib/chef_compat/resource.rb:1:in `<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in `require'
        from /home/poliva/.chefdk/gem/ruby/2.1.0/gems/chef-nexus-0.1.0/lib/chef/nexus.rb:15:in `<top (required)>'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from (irb):1
        from /opt/chefdk/embedded/bin/irb:11:in `<main>'
```

**Comment by poliva83** [comment]
To clarify... I was using 12.8.0 before (skipped 12.9.0) and there was no issue.

**Comment by lskillen** [comment]
+1

We have hit this as well, a cookbook (rsyslog) is bringing in the compat_resource cookbook at version 12.9.1 (version wasn't specified by rsyslog), but we also have the gem variant of compat_resource at version 12.9.0 which was vendored with ChefDK 0.12.0.

**Comment by lamont-granquist** [comment]
maybe related to the comment here: https://github.com/chef-cookbooks/compat_resource/pull/61#issuecomment-221699148

so something is pulling in a gem version, possible via cheffish or chef_provisioning and that is getting into a fight with compat_resource being used as a cookbook?

**Comment by lamont-granquist** [comment]
using compat_resource as a gem has been abandoned now, so the best thing to do is upgrade cheffish + chef-provisioning to a late enough version that doesn't include the dep on compat_resource as a gem and this should go away.

**Comment by poliva83** [comment]
+100 for getting rid of compat_resource :smiley_cat:
