### ISSUE TITLE
ERROR: uninitialized constant #<Class:0x00000005f9fe70>::ApplicationCookbook

### ISSUE THREAD

**Issue by davek804** [chef-cookbooks/compat_resource#65]
### Cookbook version
12.10.4

### Chef-client version
12.10.24

### Platform Details
OS X local; centos 6.5 server

### Scenario:
Run chef-client with a set of cookbooks including compat_resource 12.10.4

### Steps to Reproduce:
Have compat_resource as a required cookbook due to other cookbooks depending on it. Run chef-client. 

### Expected Result:
Chef-client completes successfully

### Actual Result:
```
Chef client fatal error: 
[2016-06-02T16:22:13-04:00] WARN: Chef::Provider::AptRepository already exists!  Cannot create deprecation class for LWRP provider apt_repository from cookbook apt
[2016-06-02T16:22:13-04:00] WARN: AptRepository already exists!  Deprecation class overwrites Custom resource apt_repository from cookbook apt

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/tomcat/resources/default.rb
================================================================================

NameError
---------
uninitialized constant #<Class:0x00000005f9fe70>::ApplicationCookbook

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/tomcat/resources/default.rb:20:in `class_from_file'
  /var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/resource/lwrp_base.rb:50:in `build_from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/tomcat/resources/default.rb:

 13:  #
 14:  # Unless required by applicable law or agreed to in writing, software
 15:  # distributed under the License is distributed on an "AS IS" BASIS,
 16:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 17:  # See the License for the specific language governing permissions and
 18:  # limitations under the License.
 19:  
 20>> include ApplicationCookbook::ResourceBase
 21:  
 22:  actions :install, :remove, :restart, :start
 23:  
 24:  attr_accessor :service_name, :clustered 
 25:  attr_accessor :http_port, :ajp_port, :ssl_port, :shutdown_port, :host_name, :session_timeout
 26:  attr_accessor :unpack_wars, :auto_deploy, :jvm_opts, :jmx_opts, :webapp_opts, :resources, :env, :roles, :users
 27:  attr_accessor :jmx_access, :jmx_access_file, :jmx_password_file, :jmx_password
 28:  attr_accessor :more_opts, :user, :context_dir, :log_dir, :tmp_dir, :work_dir, :manage_config_file
 29:  attr_accessor :webapp_dir, :base, :pid_file, :use_security_manager, :group, :shutdown_wait

Platform:
---------
x86_64-linux


Running handlers:
[2016-06-02T16:22:14-04:00] ERROR: Running exception handlers
Running handlers complete
[2016-06-02T16:22:14-04:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 04 seconds
[2016-06-02T16:22:14-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2016-06-02T16:22:14-04:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-06-02T16:22:14-04:00] ERROR: uninitialized constant #<Class:0x00000005f9fe70>::ApplicationCookbook
[2016-06-02T16:22:14-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by lamont-granquist** [comment]
there's not enough detail in this report to replicate it, the tomcat cookbook no longer includes a "resources/default.rb" file for a start.  may or may not have simply been a bug in the upstream cookbook.   looks like it depends on the old old application cookbook architecture which has been deprecated for awhile now.
