### ISSUE TITLE
chef 12.11.18 chefspec failures post version 12.10.7

### ISSUE THREAD

**Issue by bclow-invoca** [chef-cookbooks/compat_resource#89]
### Cookbook version
12.13.38

### Chef-client version
12.11.18

### Platform Details
chefspec, ubuntu 14.04

### Scenario:
Before we even try to converge or launch EC2 instances, we run unit and integration testing using chefspec and test-kitchen/serverspec. The most recent update to the compat_resource cookbook caused failures in our chefspec testing. Our serverspec testing via test-kitchen/vagrant does not appear to be effected by the changing in the compat_resource cookbook.

### Steps to Reproduce:
We are including your cookbook either directly or indirectly in six of our cookbooks that leverage AWS lwrps which we have either written or expanded upon.

### Expected Result:
We expect the tests to pass without error messages or complaints about the chefspec runners.

### Actual Result:
It will fail initially with the error:
```
/private/var/folders/wc/nhj12sj108q8yfnzj4rbkmbr0000gp/T/d20160825-98896-6oiuqg/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:643: warning: already initialized constant Chef::RunContext::ChildRunContext::CHILD_STATE
/usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/run_context.rb:661: warning: previous definition of CHILD_STATE was here
```

Then subsequent tests will fail with runtime errors:
```
Already loaded CompatResource from files/lib/compat_resource/gemspec.rb. Cannot load a second time from /private/var/folders/wc/nhj12sj108q8yfnzj4rbkmbr0000gp/T/chefspec20160825-98896-ziuvimfile_cache_path/cookbooks/compat_resource/files/lib/compat_resource/gemspec.rb
```

**Comment by lamont-granquist** [comment]
#90

**Comment by bclow-invoca** [comment]
I am still having the issue.

Indicates failure during chefspec run:
```
/private/var/folders/wc/nhj12sj108q8yfnzj4rbkmbr0000gp/T/d20160826-95580-1601b1c/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:643: warning: already initialized constant Chef::RunContext::ChildRunContext::CHILD_STATE
/usr/local/var/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/chef-12.11.18/lib/chef/run_context.rb:661: warning: previous definition of CHILD_STATE was here
```

Then an example the chefspec failure followups:
```
  1) invocaops_lib_aws::credentials clears the credentials at the end of the run
     Failure/Error: expect(resource).to subscribe_to('ruby_block[credential_noop]').on(:run).delayed

       expected "ruby_block[credential_noop]" to notify "ruby_block[clear_credentials]" with action :run delayed, but did not.

       Other notifications were:



     # ./test/unit/chefspec/credentials_spec.rb:20:in `block (2 levels) in <top (required)>'
  2) test_lwrps::create_tagged_volume creates the EBS volume
     Failure/Error:
       ChefSpec::ServerRunner.new(step_into: ['tagged_ebs_volume']) do |node|
         node.name(node_name)
         node.set['ec2']['instance_id']                            = instance_id
         node.set['ec2']['placement_availability_zone']            = az
         node.set['aws']['ebs_volume']['test_volume']['volume_id'] = volume_id
       end.converge(described_recipe)

     RuntimeError:
       Already loaded CompatResource from files/lib/compat_resource/gemspec.rb. Cannot load a second time from /private/var/folders/wc/nhj12sj108q8yfnzj4rbkmbr0000gp/T/chefspec20160826-95580-9gcly0file_cache_path/cookbooks/compat_resource/files/lib/compat_resource/gemspec.rb
     # /private/var/folders/wc/nhj12sj108q8yfnzj4rbkmbr0000gp/T/chefspec20160826-95580-9gcly0file_cache_path/cookbooks/compat_resource/files/lib/compat_resource/gemspec.rb:2:in `<top (required)>'
     # /var/folders/wc/nhj12sj108q8yfnzj4rbkmbr0000gp/T/chefspec20160826-95580-9gcly0file_cache_path/cookbooks/compat_resource/libraries/autoload.rb:13:in `require_relative'
     # /var/folders/wc/nhj12sj108q8yfnzj4rbkmbr0000gp/T/chefspec20160826-95580-9gcly0file_cache_path/cookbooks/compat_resource/libraries/autoload.rb:13:in `<top (required)>'
     # /private/var/folders/wc/nhj12sj108q8yfnzj4rbkmbr0000gp/T/d20160826-95580-1601b1c/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:185:in `load'
     # ./test/unit/chefspec/lwrp_tagged_ebs_volume_spec.rb:19:in `block (2 levels) in <top (required)>'
     # ./test/unit/chefspec/lwrp_tagged_ebs_volume_spec.rb:31:in `block (2 levels) in <top (required)>'
```

**Comment by lamont-granquist** [comment]
there hasn't been a release due to other bugs, so unless you're running master it won't be fixed

**Comment by bclow-invoca** [comment]
Alight. I assumed a closed issue and merged PR meant the issue was resolved. I see version 12.14.0 was released, but I am still having issues.

**Comment by bclow-invoca** [comment]
This is still a problem. Any resolution?
