### ISSUE TITLE
Versions > 12.10.7 break Chef 12.2 compatibility

### ISSUE THREAD

**Issue by mrdziuban** [chef-cookbooks/compat_resource#91]
### Cookbook version
\>= 12.13.37

### Chef-client version
12.2.1

### Platform Details
Ubuntu 14.04.4

### Scenario:
Run chef-client with a recipe that includes a `not_if` resource guard

### Steps to Reproduce:
Create a minimal recipe with one resource (like below) and run chef-client.

```ruby
execute 'echo' do
  command "echo test"
  not_if '[ -f /var/log/syslog ]'
end
```

### Expected Result:
chef-client to run without errors.

### Actual Result:
```
================================================================================
Error executing action `run` on resource 'execute[echo]'
================================================================================

NoMethodError
-------------
Undefined method or attribute `set_cookbook_attribute' on `node'

Cookbook Trace:
---------------
/tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:165:in `initialize'
/tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
/tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
/tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
/tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
/tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

Resource Declaration:
---------------------
# In /tmp/kitchen/cache/cookbooks/repro-test/recipes/minimal.rb

  1: execute 'echo' do
  2:   command "echo test"
  3:   not_if '[ -f /var/log/syslog ]'
  4: end

Compiled Resource:
------------------
# Declared in /tmp/kitchen/cache/cookbooks/repro-test/recipes/minimal.rb:1:in `from_file'

execute("echo") do
  action "run"
  retries 0
  retry_delay 2
  default_guard_interpreter :execute
  command "echo test"
  backup 5
  returns 0
  declared_type :execute
  cookbook_name "repro-test"
  recipe_name "minimal"
  not_if "[ -f /var/log/syslog ]"
end

[2016-08-26T13:57:30+00:00] INFO: Running queued delayed notifications before re-raising exception
[2016-08-26T13:57:30+00:00] DEBUG: Re-raising exception: NoMethodError - execute[echo] (repro-test::minimal line 1) had an error: NoMethodError: Undefined method or attribute `set_cookbook_attribute' on `node'
/opt/chef/embedded/apps/chef/lib/chef/node/attribute.rb:468:in `method_missing'
/opt/chef/embedded/apps/chef/lib/chef/node.rb:229:in `method_missing'
/tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/run_context.rb:165:in `initialize'
/opt/chef/embedded/apps/chef/lib/chef/guard_interpreter/resource_guard_interpreter.rb:96:in `new'
/opt/chef/embedded/apps/chef/lib/chef/guard_interpreter/resource_guard_interpreter.rb:96:in `get_interpreter_resource'
/opt/chef/embedded/apps/chef/lib/chef/guard_interpreter/resource_guard_interpreter.rb:28:in `initialize'
/opt/chef/embedded/apps/chef/lib/chef/guard_interpreter.rb:28:in `new'
/opt/chef/embedded/apps/chef/lib/chef/guard_interpreter.rb:28:in `for_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource/conditional.rb:59:in `configure'
/opt/chef/embedded/apps/chef/lib/chef/resource/conditional.rb:82:in `continue?'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:1073:in `block in should_skip?'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:1072:in `each'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:1072:in `find'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:1072:in `should_skip?'
/opt/chef/embedded/apps/chef/lib/chef/resource.rb:560:in `run_action'
/tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
/tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
/tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
/tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chef/embedded/apps/chef/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:331:in `block in converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:326:in `catch'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:326:in `converge'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:345:in `converge_and_save'
/opt/chef/embedded/apps/chef/lib/chef/client.rb:449:in `run'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:271:in `block in fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:259:in `fork_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:225:in `block in run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/local_mode.rb:38:in `with_server_connectivity'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:213:in `run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:392:in `block in interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `loop'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:382:in `interval_run_chef_client'
/opt/chef/embedded/apps/chef/lib/chef/application/client.rb:372:in `run_application'
/opt/chef/embedded/apps/chef/lib/chef/application.rb:60:in `run'
/opt/chef/embedded/apps/chef/bin/chef-client:26:in `<top (required)>'
/opt/chef/bin/chef-client:51:in `load'
/opt/chef/bin/chef-client:51:in `<main>'
```

Reverting to v12.10.7 resolves this issue.

**Comment by lamont-granquist** [comment]
dup, fixed in master
